export const FALLBACK_SUBSCRIPTIONS = [
  {
    id: 'sub-netflix-1',
    userId: 'user-demo-1',
    merchantId: 'merchant-netflix',
    amount: 15.99,
    currency: 'USD',
    frequency: 'MONTHLY',
    confidenceScore: 0.99,
    status: 'ACTIVE',
    userStatus: 'REVIEW',
    lastBillingDate: '2026-08-14T00:00:00.000Z',
    nextBillingDate: '2026-09-14T00:00:00.000Z',
    monthlyCost: 15.99,
    annualizedCost: 191.88,
    merchant: {
      id: 'merchant-netflix',
      normalizedName: 'Netflix',
      category: 'Entertainment',
      website: 'https://netflix.com',
      cancellationUrl: 'https://www.netflix.com/youraccount',
      cancellationInstructions: 'Log into Netflix.com -> Account -> Click "Cancel Membership".',
    },
    cancellationRequests: [],
  },
  {
    id: 'sub-spotify-2',
    userId: 'user-demo-1',
    merchantId: 'merchant-spotify',
    amount: 16.99,
    currency: 'USD',
    frequency: 'MONTHLY',
    confidenceScore: 0.98,
    status: 'ACTIVE',
    userStatus: 'KEEP',
    lastBillingDate: '2026-08-01T00:00:00.000Z',
    nextBillingDate: '2026-09-01T00:00:00.000Z',
    monthlyCost: 16.99,
    annualizedCost: 203.88,
    merchant: {
      id: 'merchant-spotify',
      normalizedName: 'Spotify',
      category: 'Music & Audio',
      website: 'https://spotify.com',
      cancellationUrl: 'https://www.spotify.com/account/change-plan/',
    },
    cancellationRequests: [],
  },
  {
    id: 'sub-planetfitness-3',
    userId: 'user-demo-1',
    merchantId: 'merchant-pf',
    amount: 24.99,
    currency: 'USD',
    frequency: 'MONTHLY',
    confidenceScore: 0.92,
    status: 'ACTIVE',
    userStatus: 'CANCEL',
    lastBillingDate: '2026-08-20T00:00:00.000Z',
    nextBillingDate: '2026-09-20T00:00:00.000Z',
    monthlyCost: 24.99,
    annualizedCost: 299.88,
    merchant: {
      id: 'merchant-pf',
      normalizedName: 'Planet Fitness',
      category: 'Fitness & Health',
      website: 'https://planetfitness.com',
      cancellationInstructions: 'Requires in-person visit to home club or Certified Postal Mail notice.',
    },
    cancellationRequests: [
      {
        id: 'req-pf-1',
        status: 'MESSAGE_GENERATED',
        method: 'AI_EMAIL',
        generatedContent: 'FORMAL NOTICE OF CANCELLATION AND REVOCATION OF PAYMENT AUTHORIZATION...',
        createdAt: '2026-08-14T00:00:00.000Z',
      },
    ],
  },
  {
    id: 'sub-chatgpt-4',
    userId: 'user-demo-1',
    merchantId: 'merchant-openai',
    amount: 20.00,
    currency: 'USD',
    frequency: 'MONTHLY',
    confidenceScore: 0.95,
    status: 'ACTIVE',
    userStatus: 'REVIEW',
    lastBillingDate: '2026-08-05T00:00:00.000Z',
    nextBillingDate: '2026-09-05T00:00:00.000Z',
    monthlyCost: 20.00,
    annualizedCost: 240.00,
    merchant: {
      id: 'merchant-openai',
      normalizedName: 'OpenAI (ChatGPT Plus)',
      category: 'SaaS & AI',
      website: 'https://chatgpt.com',
    },
    cancellationRequests: [],
  },
  {
    id: 'sub-adobe-5',
    userId: 'user-demo-1',
    merchantId: 'merchant-adobe',
    amount: 54.99,
    currency: 'USD',
    frequency: 'MONTHLY',
    confidenceScore: 0.97,
    status: 'ACTIVE',
    userStatus: 'REVIEW',
    lastBillingDate: '2026-08-18T00:00:00.000Z',
    nextBillingDate: '2026-09-18T00:00:00.000Z',
    monthlyCost: 54.99,
    annualizedCost: 659.88,
    merchant: {
      id: 'merchant-adobe',
      normalizedName: 'Adobe Creative Cloud',
      category: 'SaaS & Productivity',
      website: 'https://adobe.com',
    },
    cancellationRequests: [],
  },
];

export const FALLBACK_ANALYTICS = {
  metrics: {
    totalActiveSubscriptions: 5,
    totalMonthlySpend: 132.96,
    totalAnnualSpend: 1595.52,
    potentialAnnualSavings: 299.88,
    confirmedAnnualSavings: 0.0,
  },
  categoryBreakdown: [
    { category: 'SaaS & Productivity', monthlyCost: 54.99, count: 1 },
    { category: 'Fitness & Health', monthlyCost: 24.99, count: 1 },
    { category: 'SaaS & AI', monthlyCost: 20.00, count: 1 },
    { category: 'Music & Audio', monthlyCost: 16.99, count: 1 },
    { category: 'Entertainment', monthlyCost: 15.99, count: 1 },
  ],
  spendTrend: [
    { month: 'Sep', spend: 125.00 },
    { month: 'Oct', spend: 128.50 },
    { month: 'Nov', spend: 130.00 },
    { month: 'Dec', spend: 132.96 },
    { month: 'Jan', spend: 132.96 },
    { month: 'Feb', spend: 132.96 },
    { month: 'Mar', spend: 132.96 },
    { month: 'Apr', spend: 132.96 },
    { month: 'May', spend: 132.96 },
    { month: 'Jun', spend: 132.96 },
    { month: 'Jul', spend: 132.96 },
    { month: 'Aug', spend: 132.96 },
  ],
};
